[package]
name = "orbbs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
nom = "7.1.3"
tokio = { version = "1.33.0", features = ["full"] }
